### ISSUE TITLE
Poppler

### ISSUE THREAD

**Issue by pol-itworx** [miyako/4d-plugin-poppler#1]
![poppler issue](https://user-images.githubusercontent.com/40853904/156557557-46ce851b-78b1-4d82-8511-f4b20286c826.png)

license or privilege error ?

Plus: "Role Handlers" cannot work on silicon Mac, could you do something?

Regards, Pascal.

**Comment by AxelKohlepp** [comment]
Hello Miyako, i have the same Error. What is the solution?
![Bildschirmfoto 2022-03-22 um 23 40 59](https://user-images.githubusercontent.com/22775620/159590341-f7063fa8-f757-47a9-af70-bbc9862338b1.png)

**Comment by AxelKohlepp** [comment]
[@Keisuke_Miyako](https://discuss.4d.com/u/keisuke_miyako) : Hello - i tried 4D v19.2 and BigSur mac OS 11.6.5 results in exact the same Error!

**Comment by AxelKohlepp** [comment]
@miyako : i´m sorry - the bug is still the same with version 1.1.0 - i tried both configurations with the same result (error).
<img width="752" alt="Bildschirmfoto 2022-03-23 um 14 40 33" src="https://user-images.githubusercontent.com/22775620/159713530-e79e3aec-10b3-4147-a9e4-f57ce5b1c013.png">

**Comment by miyako** [comment]
c.f. https://discuss.4d.com/t/yet-another-pdf-text-extraction-tool/21194/6?u=keisuke_miyako

**Comment by miyako** [comment]
screenshots are not important, it is not a UI issue.

as I explained in the post above, if you run 4D from Terminal, you will see information from **dyld**.

search for poppler.

it might tell which library is missing.

**Comment by AxelKohlepp** [comment]
[@Keisuke_Miyako](https://discuss.4d.com/u/keisuke_miyako) : here ist the part with is suspicious:
2022-03-23 15:13:29.926 4D[18268:599669] Error loading /Users/admin/Desktop/medtech_v19/4d-plugin-poppler-main/poppler/test/Plugins/Poppler.bundle/Contents/MacOS/Poppler: dlopen(/Users/admin/Desktop/medtech_v19/4d-plugin-poppler-main/poppler/test/Plugins/Poppler.bundle/Contents/MacOS/Poppler, 262): Library not loaded: /Users/miyako/Desktop/intel/lib/libpoppler.64.dylib
Referenced from: /Users/admin/Desktop/medtech_v19/4d-plugin-poppler-main/poppler/test/Plugins/Poppler.bundle/Contents/MacOS/Poppler
Reason: image not found

-> Library not loaded: /Users/miyako/Desktop/intel/lib/libpoppler.64.dylib

i think there is a wrong path from your PC included?

**Comment by miyako** [comment]
I've recompiled using static linkage for Mac.

(it's a lot of work for Windows so I will leave it untouched)

**Comment by AxelKohlepp** [comment]
@miyako : Thank you - it´s working with the 1.2.0 - even with Mojave. Excellent !
